name: easydownloader

services:
   django:
     build: .
     ports:
       - "8000:8000"
     command: gunicorn config.wsgi -b 0.0.0.0:8000
     environment:
       - DJANGO_SECRET_KEY=django-insecure-nox5f%g+_r6c^z2%y@(esv!r(3-cjo8+opax_(c2=ek=8gzkw&
       - DATABASE_URL=postgresql://raufmasoumi:09011385@postgresql:5432/easydownloader
       - CELERY_BROKER_URL=redis://redis:6379/0
     volumes:
       - .:/code
     depends_on:
       - postgresql

   celery:
     build: .
     command: celery -A config worker -l INFO
     environment:
       - DJANGO_SECRET_KEY=django-insecure-nox5f%g+_r6c^z2%y@(esv!r(3-cjo8+opax_(c2=ek=8gzkw&
       - DATABASE_URL=postgresql://raufmasoumi:09011385@postgresql:5432/easydownloader
       - CELERY_BROKER_URL=redis://redis:6379/0
     volumes:
       - .:/code
     depends_on:
       - django
       - redis

   celery_beat:
     build: .
     command: celery -A config beat
     environment:
       - DJANGO_SECRET_KEY=django-insecure-nox5f%g+_r6c^z2%y@(esv!r(3-cjo8+opax_(c2=ek=8gzkw&
       - DATABASE_URL=postgresql://raufmasoumi:09011385@postgresql:5432/easydownloader
       - DJANGO_DEBUG=true
       - CELERY_BROKER_URL=redis://redis:6379/0
     volumes:
       - .:/code
     depends_on:
       - django
       - redis
       - celery

   postgresql:
     image: postgres:latest
     ports:
       - "5432:5432"
     environment:
       - POSTGRES_DB=easydownloader
       - POSTGRES_USER=raufmasoumi
       - POSTGRES_PASSWORD=09011385
     volumes:
       - postgresql_data:/var/lib/postgresql/data

   redis:
     image: redis:latest

volumes:
  postgresql_data:
