openapi: 3.0.3
info:
  title: EasyDownloader API
  version: 1.0.0
  description: Download any content easily!
paths:
  /api/download/{id}/:
    get:
      operationId: api_download_get
      description: Get the downloaded content. Waits until the download process ends
        or starts the download process.
      parameters:
      - in: path
        name: id
        schema:
          type: string
          format: uuid
        required: true
      tags:
      - api
      security:
      - cookieAuth: []
      - basicAuth: []
      - {}
      responses:
        '200':
          content:
            application/json:
              schema:
                type: string
                format: binary
          description: Downloaded content stream
        '404':
          content:
            application/json:
              schema:
                type: string
          description: Not found content
        '502':
          content:
            application/json:
              schema:
                type: string
          description: Any problem during download process
    post:
      operationId: api_download_post
      description: Get the downloaded content. Waits until the download process ends
        or starts the download process.
      parameters:
      - in: path
        name: id
        schema:
          type: string
          format: uuid
        required: true
      tags:
      - api
      security:
      - cookieAuth: []
      - basicAuth: []
      - {}
      responses:
        '200':
          content:
            application/json:
              schema:
                type: string
                format: binary
          description: Downloaded content stream
        '404':
          content:
            application/json:
              schema:
                type: string
          description: Not found content
        '502':
          content:
            application/json:
              schema:
                type: string
          description: Any problem during download process
  /api/getinfo/:
    get:
      operationId: api_getinfo_get
      description: Get info of the given URL
      parameters:
      - in: query
        name: audio_bitrate
        schema:
          type: integer
          default: 400
        description: Bitrate of the audio content.
      - in: query
        name: extension
        schema:
          type: string
          enum:
          - aac
          - mkv
          - mov
          - mp3
          - mp4
          - wav
          default: mp3
        description: The output file format of the downloaded content.
      - in: query
        name: frame_rate
        schema:
          type: integer
        description: Frame rate of the video content (as fps).
      - in: query
        name: resolution
        schema:
          type: integer
          default: 360
        description: Resolution of the video content (as pixels). Better to pass from
          the list [144, 240, 360, 480, 720, 1080].
      - in: query
        name: type
        schema:
          type: string
          enum:
          - audio
          - video
          default: audio
        description: The type of content to download.
      - in: query
        name: url
        schema:
          type: string
        description: The URL of the content to download.
        required: true
      tags:
      - api
      security:
      - cookieAuth: []
      - basicAuth: []
      - {}
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ContentInfo'
          description: ''
        '400':
          content:
            application/json:
              schema:
                type: string
          description: Invalid query params
        '502':
          content:
            application/json:
              schema:
                type: string
          description: Any problem during info extraction process
    post:
      operationId: api_getinfo_post
      description: Get info of the given URL
      tags:
      - api
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/URLDetail'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/URLDetail'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/URLDetail'
        required: true
      security:
      - cookieAuth: []
      - basicAuth: []
      - {}
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ContentInfo'
          description: ''
        '400':
          content:
            application/json:
              schema:
                type: string
          description: Invalid query params
        '502':
          content:
            application/json:
              schema:
                type: string
          description: Any problem during info extraction process
components:
  schemas:
    ContentInfo:
      type: object
      properties:
        pk:
          type: string
          format: uuid
        url:
          type: string
          format: uri
          maxLength: 400
        title:
          type: string
          maxLength: 300
        duration:
          type: string
          maxLength: 50
        thumbnail_url:
          type: string
          format: uri
          maxLength: 400
        webpage_url_domain:
          type: string
          maxLength: 300
        file_size:
          type: string
          nullable: true
          maxLength: 100
        upload_date:
          type: string
          maxLength: 100
        description:
          type: string
          nullable: true
          maxLength: 500
        track:
          type: string
          nullable: true
          maxLength: 300
        artist:
          type: string
          nullable: true
          maxLength: 300
        album:
          type: string
          nullable: true
          maxLength: 300
        release_date:
          type: string
          nullable: true
          maxLength: 100
        channel:
          type: string
          nullable: true
          maxLength: 300
        uploader:
          type: string
          nullable: true
          maxLength: 300
      required:
      - duration
      - pk
      - thumbnail_url
      - title
      - url
      - webpage_url_domain
    ExtensionEnum:
      enum:
      - mp4
      - mkv
      - mov
      - mp3
      - aac
      - wav
      type: string
      description: |-
        * `mp4` - mp4
        * `mkv` - mkv
        * `mov` - mov
        * `mp3` - mp3
        * `aac` - aac
        * `wav` - wav
    TypeEnum:
      enum:
      - video
      - audio
      type: string
      description: |-
        * `video` - video
        * `audio` - audio
    URLDetail:
      type: object
      properties:
        url:
          type: string
          format: uri
          maxLength: 400
        type:
          allOf:
          - $ref: '#/components/schemas/TypeEnum'
          default: audio
        extension:
          allOf:
          - $ref: '#/components/schemas/ExtensionEnum'
          default: mp3
        resolution:
          type: integer
          default: 360
        frame_rate:
          type: integer
        aspect_ratio:
          type: integer
        audio_bitrate:
          type: integer
          default: 400
      required:
      - url
  securitySchemes:
    basicAuth:
      type: http
      scheme: basic
    cookieAuth:
      type: apiKey
      in: cookie
      name: sessionid
