openapi: 3.0.3
info:
  title: ''
  version: 0.0.0
paths:
  /api/download/{id}/:
    get:
      operationId: api_download_retrieve
      parameters:
      - in: path
        name: id
        schema:
          type: string
          format: uuid
        required: true
      tags:
      - api
      security:
      - cookieAuth: []
      - basicAuth: []
      - {}
      responses:
        '200':
          description: No response body
    post:
      operationId: api_download_create
      parameters:
      - in: path
        name: id
        schema:
          type: string
          format: uuid
        required: true
      tags:
      - api
      security:
      - cookieAuth: []
      - basicAuth: []
      - {}
      responses:
        '200':
          description: No response body
  /api/getinfo/:
    get:
      operationId: api_getinfo_retrieve
      tags:
      - api
      security:
      - cookieAuth: []
      - basicAuth: []
      - {}
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ContentInfo'
          description: ''
    post:
      operationId: api_getinfo_create
      tags:
      - api
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ContentInfo'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/ContentInfo'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/ContentInfo'
        required: true
      security:
      - cookieAuth: []
      - basicAuth: []
      - {}
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ContentInfo'
          description: ''
  /api/schema/:
    get:
      operationId: api_schema_retrieve
      description: |-
        OpenApi3 schema for this API. Format can be selected via content negotiation.

        - YAML: application/vnd.oai.openapi
        - JSON: application/vnd.oai.openapi+json
      parameters:
      - in: query
        name: format
        schema:
          type: string
          enum:
          - json
          - yaml
      - in: query
        name: lang
        schema:
          type: string
          enum:
          - af
          - ar
          - ar-dz
          - ast
          - az
          - be
          - bg
          - bn
          - br
          - bs
          - ca
          - ckb
          - cs
          - cy
          - da
          - de
          - dsb
          - el
          - en
          - en-au
          - en-gb
          - eo
          - es
          - es-ar
          - es-co
          - es-mx
          - es-ni
          - es-ve
          - et
          - eu
          - fa
          - fi
          - fr
          - fy
          - ga
          - gd
          - gl
          - he
          - hi
          - hr
          - hsb
          - hu
          - hy
          - ia
          - id
          - ig
          - io
          - is
          - it
          - ja
          - ka
          - kab
          - kk
          - km
          - kn
          - ko
          - ky
          - lb
          - lt
          - lv
          - mk
          - ml
          - mn
          - mr
          - ms
          - my
          - nb
          - ne
          - nl
          - nn
          - os
          - pa
          - pl
          - pt
          - pt-br
          - ro
          - ru
          - sk
          - sl
          - sq
          - sr
          - sr-latn
          - sv
          - sw
          - ta
          - te
          - tg
          - th
          - tk
          - tr
          - tt
          - udm
          - ug
          - uk
          - ur
          - uz
          - vi
          - zh-hans
          - zh-hant
      tags:
      - api
      security:
      - cookieAuth: []
      - basicAuth: []
      - {}
      responses:
        '200':
          content:
            application/vnd.oai.openapi:
              schema:
                type: object
                additionalProperties: {}
            application/yaml:
              schema:
                type: object
                additionalProperties: {}
            application/vnd.oai.openapi+json:
              schema:
                type: object
                additionalProperties: {}
            application/json:
              schema:
                type: object
                additionalProperties: {}
          description: ''
components:
  schemas:
    ContentInfo:
      type: object
      properties:
        pk:
          type: string
          format: uuid
        url:
          type: string
          format: uri
          maxLength: 400
        title:
          type: string
          maxLength: 300
        duration:
          type: string
          format: time
          nullable: true
        duration_string:
          type: string
          maxLength: 50
        thumbnail_url:
          type: string
          format: uri
          maxLength: 400
        webpage_url_domain:
          type: string
          maxLength: 300
        file_size:
          type: string
          nullable: true
          maxLength: 100
        upload_date:
          type: string
          format: date-time
          nullable: true
        upload_date_string:
          type: string
          maxLength: 100
        description:
          type: string
          nullable: true
          maxLength: 500
        track:
          type: string
          nullable: true
          maxLength: 300
        artist:
          type: string
          nullable: true
          maxLength: 300
        album:
          type: string
          nullable: true
          maxLength: 300
        release_date:
          type: string
          format: date-time
          nullable: true
        release_date_string:
          type: string
          nullable: true
          maxLength: 100
        channel:
          type: string
          nullable: true
          maxLength: 300
        uploader:
          type: string
          nullable: true
          maxLength: 300
      required:
      - duration_string
      - pk
      - thumbnail_url
      - title
      - upload_date_string
      - url
      - webpage_url_domain
  securitySchemes:
    basicAuth:
      type: http
      scheme: basic
    cookieAuth:
      type: apiKey
      in: cookie
      name: sessionid
