# Generated by Django 5.1.5 on 2025-01-26 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('downloader', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='expiration_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
