# Generated by Django 5.1.5 on 2025-02-03 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('downloader', '0002_alter_content_expiration_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='download_path',
            field=models.FilePathField(blank=True, null=True),
        ),
    ]
