# Generated by Django 5.1.5 on 2025-02-03 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('downloader', '0003_content_download_path'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='download_path',
            field=models.FilePathField(blank=True, null=True, path='temp/'),
        ),
    ]
