# Generated by Django 5.1.5 on 2025-02-18 17:25

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('downloader', '0004_alter_content_download_path'),
    ]

    operations = [
        migrations.CreateModel(
            name='AllowedExtractor',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=300)),
                ('regex', models.CharField(max_length=300)),
                ('active', models.BooleanField(blank=True, default=True)),
                ('main_extractor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detailed_extractors', to='downloader.allowedextractor')),
            ],
        ),
    ]
