# Generated by Django 5.1.5 on 2025-02-18 17:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('downloader', '0005_allowedextractor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allowedextractor',
            name='main_extractor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='detailed_extractors', to='downloader.allowedextractor'),
        ),
    ]
