# Generated by Django 5.1.5 on 2025-02-27 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('downloader', '0006_alter_allowedextractor_main_extractor'),
    ]

    operations = [
        migrations.RenameField(
            model_name='content',
            old_name='name',
            new_name='title',
        ),
        migrations.AddField(
            model_name='content',
            name='expired',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AddField(
            model_name='content',
            name='info_file_path',
            field=models.FilePathField(default='Unknown', path='info/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='content',
            name='info_id',
            field=models.CharField(default='Uknown', max_length=300),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='content',
            name='successful',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='content',
            name='url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
