# Generated by Django 5.1.6 on 2025-03-18 12:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('downloader', '0007_rename_name_content_title_content_expired_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='content',
            old_name='successful',
            new_name='downloaded_successfully',
        ),
    ]
