# Generated by Django 5.1.6 on 2025-03-21 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('downloader', '0008_rename_successful_content_downloaded_successfully'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='celery_download_task_id',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
