# Generated by Django 5.1.6 on 2025-03-26 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('downloader', '0009_content_celery_download_task_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='aspect_ratio',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='content',
            name='bitrate',
            field=models.IntegerField(blank=True, default=400, null=True),
        ),
        migrations.AddField(
            model_name='content',
            name='extension',
            field=models.CharField(blank=True, choices=[('video', [('mp4', 'mp4'), ('mkv', 'mkv'), ('mov', 'mov')]), ('audio', [('mp3', 'mp3'), ('aac', 'aac'), ('wav', 'wav')])], default='mp3', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='content',
            name='frame_rate',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='content',
            name='resolution',
            field=models.IntegerField(blank=True, default=360, null=True),
        ),
        migrations.AddField(
            model_name='content',
            name='type',
            field=models.CharField(blank=True, choices=[('video', 'video'), ('audio', 'audio')], default='audio', max_length=20, null=True),
        ),
    ]
