# Generated by Django 5.1.7 on 2025-03-29 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('downloader', '0010_content_aspect_ratio_content_bitrate_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='content',
            old_name='bitrate',
            new_name='audio_bitrate',
        ),
        migrations.AlterField(
            model_name='content',
            name='extension',
            field=models.CharField(blank=True, default='mp3', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='content',
            name='type',
            field=models.CharField(blank=True, default='audio', max_length=20, null=True),
        ),
    ]
