# Generated by Django 5.1.7 on 2025-07-15 10:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('downloader', '0011_rename_bitrate_content_audio_bitrate_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='content',
            options={'ordering': ['-processed_at']},
        ),
    ]
